name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --production
    
    - name: Run tests
      run: npm test
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Build Docker image
      run: |
        docker build -t moosh-wallet:${{ github.sha }} .
        docker tag moosh-wallet:${{ github.sha }} moosh-wallet:latest
    
    - name: Deploy to production
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # Example: kubectl apply -f k8s/
        # Example: docker push to registry
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - See [CHANGELOG.md](CHANGELOG.md) for details
        draft: false
        prerelease: false